// error handling can be done by try catch throw finally

try{
console.log(test); // example for error
}
catch (error){
  console.log("");
}